### ISSUE TITLE
使用Travis CI自动部署Hexo到GitHub | Dmego的博客

### ISSUE THREAD

**Issue by dmego** [dmego/dmego.github.io#18]
http://dmego.me/2017/10/13/deylpoy-hexo-with-TravisCI.html 

 前言使用 hexo + gitPages 搭建个人博客的人都知道，每当要发表一篇博文，第一步得手动使用 hexo g 命令生成静态网页，然后还得通过 hexo d 命令将静态文件推送到GitHub远程仓库,不说麻烦不麻烦，更重要的是有时候环境换了，没有搭建 hexo 环境，想发篇博客的时候就没有可能了。而现在通过 Travis CI 就能自动构建自己的博客。而我们只需将写好的 Markdown 格

**Comment by isecret** [comment]
确实是个挺不错的工具，不过我很好奇能否使用 gulp？因为我在推静态文件之前会将所有文件进行压缩，减小文件体积。

**Comment by dmego** [comment]
> @isecret
> 确实是个挺不错的工具，不过我很好奇能否使用 gulp？因为我在推静态文件之前会将所有文件进行压缩，减小文件体积。

我试过gulp,不过遇到一个问题，他会把一些js或者css 压缩在一起，这样导致FontAwesome的js还是css无法使用，博客上的一些图标显示不出来

**Comment by zzqzzqzzqsc03** [comment]
**怎么推送？？？orz，一直用不懂git**

**Comment by dmego** [comment]
> @zzqzzqzzqsc03
> **怎么推送？？？orz，一直用不懂git**

不懂 Git 可以看看廖雪峰的Git教程；推送的话如果不想用命令，可以用 vscode，编辑完直接推送，非常方便

**Comment by zzqzzqzzqsc03** [comment]
vsc怎么推送？？？

**Comment by dmego** [comment]
> @zzqzzqzzqsc03
> vsc怎么推送？？？

 搜一下网上的教程,非常多

**Comment by zzqzzqzzqsc03** [comment]
> @dmego
> > @zzqzzqzzqsc03
> > vsc怎么推送？？？
> 
>  搜一下网上的教程,非常多

谢谢
