### ISSUE TITLE
汉诺塔的图解递归算法 | Dmego的博客

### ISSUE THREAD

**Issue by dmego** [dmego/dmego.github.io#19]
http://dmego.me/2016/10/16/hanoi.html 

 起源汉诺塔（又称河内塔）问题是源于印度一个古老传说的益智玩具。大梵天创造世界的时候做了三根金刚石柱子，在一根柱子上从下往上按照大小顺序摞着64片黄金圆盘。大梵天命令婆罗门把圆盘从下面开始按大小顺序重新摆放在另一根柱子上。并且规定，在小圆盘上不能放大圆盘，在三根柱子之间一次只能移动一个圆盘。 抽象为数学问题如下图所示，从左到右有A、B、C三根柱子，其中A柱子上面有从小叠到大的n个圆盘，现要求将A柱子

**Comment by n2meetu** [comment]
清晰

**Comment by xieweizhi** [comment]
错别字：
同过递归来求 -> 通过
