### ISSUE TITLE
微信小程序：出发吧一起 | Dmego的博客

### ISSUE THREAD

**Issue by dmego** [dmego/dmego.github.io#22]
http://dmego.me/2017/12/04/wechat-app-together.html 

 前言经过将近一个多月的开发,我们团队开发的微信小程序 “出发吧一起” 终于开发完成,现在的线上版本为 2.2.4-beta 版 本文档主要介绍该小程序在开发中所用到的技术,已经在开发中遇到问题的采取的解决方法 小程序简介“让兴趣不再孤单，让爱好不再流浪” 是微信小程序《出发吧一起》的主题，这款小程序旨在解决当代大学生在

**Comment by a2501521908** [comment]
发现博主~~ 的背景好科幻的感觉 大神好~

**Comment by liujibin** [comment]
背景太晃眼，会分散阅读的注意力，建议去掉。

**Comment by dmego** [comment]
> @liujibin
> 背景太晃眼，会分散阅读的注意力，建议去掉。

嗯嗯，最近没有时间，等什么时候有时间再整整博客页面

**Comment by pzuopin** [comment]
想问一下 我下载了项目如何启动， 需要注册bmob帐号吗  
启动时有报错 17个文件找不到  我先看看啊

**Comment by dmego** [comment]
@pzuopin需要注册bmob，你可以直接在bmob的源码交易栏目找到出发吧一起，也是免费的，购买后可以不用建表

**Comment by HEUDavid** [comment]
牛皮牛皮，真是很棒
