### ISSUE TITLE
软件架构师如何工作 | Dmego的博客

### ISSUE THREAD

**Issue by dmego** [dmego/dmego.github.io#23]
http://dmego.me/2018/03/08/Software-Architect-how-to-work.html 

 前言要想了解软件架构师如何工作，首先要搞清楚这么几个问题：什么是架构，怎样理解架构，如何做好架构，什么是软件，什么是软件架构师，软件架构师的工作是什么，怎么理清技术、业务和架构三者的关系。资深架构师王概凯在《架构漫谈》系列专栏中一一给出了这些问题的答案。本文也是本人阅读《架构漫谈》时所做的笔记与思考。 什么是架构什么是架构，为什么会产生架构，作者由人类社会的演化，人类社会中分工的出现来引入问题的答

**Comment by hubojing** [comment]
博主是架构师吗

**Comment by dmego** [comment]
> @hubojing
> 博主是架构师吗

这是一篇读书笔记，本人还是学生，离架构师还差好远😂
