### ISSUE TITLE
基于ubuntu16.04部署IBM开源区块链项目-弹珠资产管理(Marbles) | Dmego的博客

### ISSUE THREAD

**Issue by dmego** [dmego/dmego.github.io#25]
http://dmego.me/2018/05/15/deploy-IBM-blockchain-marbles.html 

 前言本教程基本上是对Marbles项目的翻译过程. 如果英文比较好的话，建议根据官方操作说明,一步步进行环境部署。当然你也可以参考本教程在自己的主机上部署该项目。 Marbles 介绍关于 Marbles 这个应用程序的基础网络是 Hyperledger Fabric，后者是一个 Linux Foundation 项目。 您可能想查阅以下操作说明来稍微了解一下 Hyperledger Fabr

**Comment by isecret** [comment]
[Secret Blog](https://blog.isecret.vip/) 改名为 [WangMao's Blog](https://blog.wangmao.me/) ，原域名已经停止 301 重定向了，请修改一下~

**Comment by dmego** [comment]
OK

Mao Wang <notifications@github.com> 于2018年8月17日周五 上午9:59写道：

**Comment by dmego** [comment]
> @ssy1997
> 你好，我在sudo bash setup_script.sh这一步一直下不下来，速度还特别慢，请问怎么处理呢

添加阿里云的Docker Hub镜像试试, 或者DaoClound的镜像

**Comment by ssy1997** [comment]
> @dmego
> > @ssy1997
> > 你好，我在sudo bash setup_script.sh这一步一直下不下来，速度还特别慢，请问怎么处理呢
> 
> 添加阿里云的Docker Hub镜像试试, 或者DaoClound的镜像

我已经按照您的第一篇部署了环境，那这一步的镜像是可以不用了吗？抱歉，我还不是特别熟悉，刚入门。

**Comment by dmego** [comment]
> @ssy1997
> > @dmego
> > > @ssy1997
> > > 你好，我在sudo bash setup_script.sh这一步一直下不下来，速度还特别慢，请问怎么处理呢
> > 
> > 添加阿里云的Docker Hub镜像试试, 或者DaoClound的镜像
> 
> 我已经按照您的第一篇部署了环境，那这一步的镜像是可以不用了吗？抱歉，我还不是特别熟悉，刚入门。
如果按照上一篇部署成功了的话,这里就不必再下镜像了.

**Comment by ssy1997** [comment]
> @dmego
> > @ssy1997
> > > @dmego
> > > > @ssy1997
> > > > 你好，我在sudo bash setup_script.sh这一步一直下不下来，速度还特别慢，请问怎么处理呢
> > > 
> > > 添加阿里云的Docker Hub镜像试试, 或者DaoClound的镜像
> > 
> > 我已经按照您的第一篇部署了环境，那这一步的镜像是可以不用了吗？抱歉，我还不是特别熟悉，刚入门。
> 如果按照上一篇部署成功了的话,这里就不必再下镜像了.
> 

感谢
