### ISSUE TITLE
基于ubuntu16.04快速构建Hyperledger Fabric网络 | Dmego的博客

### ISSUE THREAD

**Issue by dmego** [dmego/dmego.github.io#26]
http://dmego.me/2018/05/14/quick-start-hyperledger-fabric.html#more 

 前言最近在参加一个比赛,使用到了区块链的开源软件hyperledger,由于之前从未接触过区块链,以及和区块链开发相关的内容,所有在网上查阅了大量的资料,并且通过学习yeasy(杨宝华)开源的入门书籍区块链技术指南以及进阶学习的《区块链原理、设计与应用》,对区块链的一些相关概念有了一定认识。这里记录的是我安装hyperledger fabric的所有步骤，同时也是一个快速搭建单机环境的参考教程

**Comment by jinjiaKarl** [comment]
今天三月份看的fabric，当时走了很多坑，就只到了链码阶段，sdk就已经放弃了。看到你的IT技能，作为比你小一届的大学生，自愧不如呀，加油
