### ISSUE TITLE
友情链接 | Hexo

### ISSUE THREAD

**Issue by dmego** [dmego/dmego.github.io#28]
http://dmego.me/links/

**Comment by dakego** [comment]
朋友你好，可以交换友链吗，dakego.me

**Comment by dmego** [comment]
可以

**Comment by x931890193** [comment]
老哥， 你好，能加个友链吗？https://www.mongona.com

**Comment by dmego** [comment]
> @x931890193
> 老哥， 你好，能加个友链吗？https://www.mongona.com

可以，已添加
